#+title: What I'm doing now
#+description: What I'm doing now | Fritz Grabo

Updated October 2025.

* Punk rock energy

As a teen through my early thirties, I lived on Punk rock -- British street punk and early hardcore punk of the late 70s / early 80s. The raw energy and attitude resonated with me, they felt like the perfect soundtrack for my life. When I settled into steadier rhythms (regular working hours, steady income, family, kids), so did the music: Psytrance pulled me through hours of meditative, focused programming flow, monotonically, powerful: a linear motion.

With the recent end of a soothing retainer contract that had lasted for 12 years (see below), and maybe a touch of midlife crisis, I find myself fallen off of the train and listening to Punk rock all day long. This was not a conscious decision, I didn't see this coming at all. Talk about subconscious.

Now, I'm checking to see what's happened in Punk in the last 10 years and notice that I'm still hooked on [[https://en.wikipedia.org/wiki/Angelic_Upstarts][the]] [[https://en.wikipedia.org/wiki/Cock_Sparrer][old]] [[https://en.wikipedia.org/wiki/Minor_Threat][stuff]] -- recent groups seem to have a different type of energy. Is it me? I'm sure it's out there though, so if you have recommendations, [[file:../contact/index.org][shoot me an email]]!

* Both kids in school

Finally, our youngest has finished kindergarten and is joining her brother at school. We'll miss our beloved forest kindergarten, but we definitely won't miss the 30‑minute drive it used to take us every day. School life is good, and intense. We chose a community‑run, rather alternative school and dove in head‑first by signing up for the club board, i.e. cat herding. It's quite an adventure, but we're enjoying it! (Ask again in 9 years.)

* Finding out what's next

The U.S.-based company I've helped grow from a lean startup into a leading technology provider over the past 12 years has been acquired (yay, start-up success!), and that brought a massive layoff that included me as a contractor (oh no, capitalism!). I'm genuinely grateful to have been on that wild ride, and to have worked alongside so many amazing, talented people. I want to see this as an opportunity to take a short break, re-assess my priorities, and find a project that excites me, both from a tech perspective, and in terms of mission.

* "Hell yeah or no"

I'm working through Derek Sivers' book "Hell yeah or no", at the slow pace of just one to two chapters a day. The books helps me find the right questions to ask, and the pace leaves enough time to get a feeling for their answers. This is much connected to the topic above obviously: I intend to get a better understanding of what I offer and what I want, both professionally, and in life generally (no pressure, Derek!). The daily routine of working for a single company for 12 years provided a dependable, defining, yet constricting frame that is gone now. It's a thing of the past, and I can no longer use it to orient myself. Exciting times.

* Living next to the woods

It's been two years now since we moved into the house. We're done swapping out the windows and are now busy planning a full overhaul of the massive tiled stove that keeps us warm in the winter. The real standout, though, is the garden that spills straight into the forest, giving us free, direct access to the woods -- being able to take a stroll to do some deep thinking or to clear my head is invaluable and has become an almost daily routine.
