#+title: Fritz Grabo
#+description: The personal website of Fritz Grabo

#+html_head_extra: <meta name="twitter:card" content="summary">
#+html_head_extra: <meta name="twitter:site" content="@fritzgrabo">
#+html_head_extra: <meta name="twitter:title" content="Fritz Grabo">
#+html_head_extra: <meta name="twitter:description" content="The personal website of Fritz Grabo.">
#+html_head_extra: <meta name="og:title" content="Fritz Grabo">
#+html_head_extra: <meta name="og:description" content="The personal website of Fritz Grabo.">

* 10 seconds

I'm a *@@html:<mark>@@self-employed senior software engineer and consultant@@html:</mark>@@* with 20+ years experience in building and scaling web applications, neatly tucked away near the woods in Austria with my partner and our two kids.

* On work

I'm passionate about solving challenging and meaningful problems that help make the world a better place. Specifically, ...

- [[file:work/collaborate/index.org][I work embedded in your team]] to boost its effectiveness.
- [[file:work/execute/index.org][I architect and implement software projects]] from A to Z.
- [[file:work/consult/index.org][I consult on tech topics]], drawing from 20+ years of experience.

Technology-wise, my focus tends to fall on the backend and operations side of things, though I enjoy working on all parts and levels of a system. My preferred stack includes Ruby, Rails, PostgreSQL, and HTML/CSS/Hotwire. For operations, I'm comfortable with everything from old-school root servers to modern cloud solutions like Google Cloud or Kubernetes.

If one of these sound like a match, do [[file:contact/index.org][reach out!]]

* Network

I've worked with these awesome folks on many, many successful projects throughout the years. We regularly team up to tackle the challenging, bigger projects together: @@html:<a href="https://wolfgangrittner.dev" target="_blank">Wolfgang</a>@@, @@html:<a href="https://christoph.luppri.ch" target="_blank">Christoph</a>@@, @@html:<a href="https://embedded-focus.com" target="_blank">Rainer</a>@@.

* More

- Check out the [[file:now/index.org]["now" page]] to see what I'm doing now.
- Flip through [[file:posts/index.org][the blog posts]] for more in-depth thoughts on +life+ Emacs, mostly.
- Browse the @@html:<a href="https://github.com/fritzgrabo" target="_blank">GitHub profile</a>@@ if you're interested in my Open Source work.
