#+title: Fritz Grabo
#+description: The personal website of Fritz Grabo

#+html_head_extra: <meta name="twitter:card" content="summary">
#+html_head_extra: <meta name="twitter:site" content="@fritzgrabo">
#+html_head_extra: <meta name="twitter:title" content="Fritz Grabo">
#+html_head_extra: <meta name="twitter:description" content="The personal website of Fritz Grabo.">
#+html_head_extra: <meta name="og:title" content="Fritz Grabo">
#+html_head_extra: <meta name="og:description" content="The personal website of Fritz Grabo.">

* 10 seconds

I'm a *@@html:<mark>@@self-employed senior software engineer and consultant@@html:</mark>@@* with 20+ years experience in building and scaling web applications, neatly tucked away near the woods in Austria with my partner and our two kids.

* On work

I'm passionate about solving challenging and meaningful problems that help make the world a better place.

Technology-wise, my focus tends to fall on the backend and operations side of things, though I enjoy working on all parts and levels of a system. My preferred stack includes Ruby, Rails, PostgreSQL, and HTML/CSS/Hotwire. For operations, I'm comfortable with everything from old-school root servers to modern cloud solutions like Google Cloud or Kubernetes.

@@html:&bull;&ensp;@@ *I work embedded in your team to boost its effectiveness.* I enjoy collaborating with fellow engineers, designers, product managers and customers to ship reliable, elegant software. Clients @@html:<a href="https://www.linkedin.com/in/fritzgrabo/details/recommendations" target="_blank">@@have valued@@html:</a>@@ my positive effect on team culture, my mentoring mindset, and the overall level of quality I help establish in all the little details. I've worked remotely for most of my career and thrive in distributed teams.

@@html:&bull;&ensp;@@ *I architect and implement software projects from A to Z for startups and businesses.* I dig deep until we both grok your actual needs, then create a simple, turnkey solution that meets them perfectly. Expect boring, trusted technology and a deliverable that's easy to understand, operate, and maintain long-term.

@@html:&bull;&ensp;@@ *I draw from 20+ years of experience to consult on tech topics.* Let's just say I've seen a lot so you don't have to :) Specifically, if you're growing fast and want to get it right the first time, I will help defuse the costly gotchas, validate your approach, and guide your decisions.

If one of these sound like a match, do [[file:contact/index.org][reach out!]]

* More

- Check out the [[file:now/index.org]["now" page]] to see what I'm doing now.
- Flip through [[file:posts/index.org][the blog posts]] for more in-depth thoughts on +life+ Emacs, mostly.
- Browse the @@html:<a href="https://github.com/fritzgrabo" target="_blank">GitHub profile</a>@@ if you're interested in my Open Source work.
